#!/usr/bin/env python3
"""
Frappe starter — idempotent, crash-resilient, fast startup.

Boot logic:
  FIRST BOOT with baked DB (/home/frappe/frappe_baked.sql.gz exists):
    1. Start local Redis on 127.0.0.1:6380
    2. Write common_site_config.json pointing at local Redis
    3. Wait for MariaDB
    4. Create DB + user via mysql CLI
    5. Import baked SQL dump (~30s, all DocTypes pre-installed)
    6. Write site_config.json
    7. bench migrate --skip-search-index (fast schema diff, ~2 min)
    8. bench install-app crm
    9. Switch common_site_config.json to real Redis
    10. exec gunicorn

  FIRST BOOT without baked DB (fallback):
    1-3. Same as above
    4. bench new-site (creates DB, imports SQL, installs all DocTypes, ~90 min)
    5. bench install-app crm
    6. Switch to real Redis
    7. exec gunicorn

  RESUME BOOT (site_config.json absent, DB EXISTS from crashed run):
    1-3. Same as above
    4. Write site_config.json
    5. bench migrate --skip-search-index (resumes from where crash happened)
    6. bench install-app crm (if not already installed)
    7. Switch to real Redis
    8. exec gunicorn

  SUBSEQUENT BOOTS (site_config.json present on persistent disk):
    1-3. Same as above
    4. bench migrate --skip-search-index  (~30s)
    5. Switch to real Redis
    6. exec gunicorn

Health endpoints (always available from second 0):
  GET /health          → 200 OK
  GET /api/method/ping → 200 OK
  GET /setup-log       → full log as plain text
"""
import os
import sys
import json
import time
import threading
import subprocess
import socket
from http.server import HTTPServer, BaseHTTPRequestHandler

# ── Configuration ─────────────────────────────────────────────────────────────
BENCH_DIR   = "/home/frappe/frappe-bench"
SITE        = os.environ.get("FRAPPE_SITE_NAME", "crm.localhost")
DB_HOST     = os.environ.get("DB_HOST", "mariadb")
DB_PORT     = int(os.environ.get("DB_PORT", "10000"))
DB_NAME     = os.environ.get("DB_NAME", "crm_db")
DB_PASS     = os.environ.get("DB_PASSWORD", "changeme")
DB_ROOT     = os.environ.get("DB_ROOT_PASSWORD", "")
ADMIN_PW    = os.environ.get("ADMIN_PASSWORD", "admin")
ENC_KEY     = os.environ.get("ENCRYPTION_KEY", "")
REDIS_CACHE = os.environ.get("REDIS_CACHE_URL", "redis://crm-redis-cache:10000")
REDIS_QUEUE = os.environ.get("REDIS_QUEUE_URL", "redis://crm-redis-queue:10000")
SERVE_PORT  = int(os.environ.get("PORT", "8000"))

# Local Redis for migrate (avoids dependency on external Redis during setup)
LOCAL_REDIS_PORT = 6380
LOCAL_REDIS_URL  = f"redis://127.0.0.1:{LOCAL_REDIS_PORT}"

# Baked DB dump (generated by GitHub Actions CI, included in Docker image)
BAKED_DB_PATH = "/home/frappe/frappe_baked.sql.gz"

LOG_LINES     = []
SETUP_DONE    = threading.Event()
SETUP_SUCCESS = False
_local_redis_proc = None

# ── Logging ───────────────────────────────────────────────────────────────────
def log(msg):
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    LOG_LINES.append(line)
    try:
        with open("/tmp/frappe_setup.log", "a") as f:
            f.write(line + "\n")
    except Exception:
        pass

# ── Health server ─────────────────────────────────────────────────────────────
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/setup-log":
            body = "\n".join(LOG_LINES).encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path in ("/health", "/api/method/ping"):
            body = b"OK"
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Content-Length", "2")
            self.end_headers()
            self.wfile.write(body)
        else:
            if SETUP_DONE.is_set() and not SETUP_SUCCESS:
                body = b"Setup FAILED - see /setup-log\n"
                self.send_response(503)
            else:
                body = b"Frappe CRM - initializing...\n"
                self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
    def log_message(self, *a):
        pass

# ── TCP helpers ───────────────────────────────────────────────────────────────
def wait_for_tcp(host, port, label=None, timeout=300):
    label = label or f"{host}:{port}"
    log(f"Waiting for {label} ({host}:{port})...")
    start = time.time()
    attempt = 0
    while time.time() - start < timeout:
        try:
            s = socket.create_connection((host, port), timeout=5)
            s.close()
            log(f"{label} ready after {int(time.time()-start)}s")
            return True
        except Exception as e:
            if attempt % 10 == 0:
                log(f"  {label} not ready (attempt {attempt+1}): {e}")
            attempt += 1
            time.sleep(3)
    log(f"ERROR: {label} timeout after {timeout}s")
    return False

# ── Local Redis ───────────────────────────────────────────────────────────────
def start_local_redis():
    global _local_redis_proc
    log(f"Starting local Redis on port {LOCAL_REDIS_PORT}...")

    redis_bin = None
    for path in ["/usr/bin/redis-server", "/usr/local/bin/redis-server"]:
        if os.path.exists(path):
            redis_bin = path
            break

    if not redis_bin:
        log("redis-server not found, installing...")
        r = subprocess.run(
            ["apt-get", "install", "-y", "--no-install-recommends", "redis-server"],
            capture_output=True, text=True
        )
        if r.returncode == 0:
            redis_bin = "/usr/bin/redis-server"
        else:
            log(f"Could not install redis-server: {r.stderr[:200]}")
            return False

    try:
        _local_redis_proc = subprocess.Popen(
            [redis_bin, "--port", str(LOCAL_REDIS_PORT),
             "--bind", "127.0.0.1",
             "--save", "",
             "--loglevel", "warning"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        for _ in range(20):
            try:
                s = socket.create_connection(("127.0.0.1", LOCAL_REDIS_PORT), timeout=1)
                s.close()
                log(f"Local Redis ready on port {LOCAL_REDIS_PORT}")
                return True
            except Exception:
                time.sleep(0.5)
        log("ERROR: Local Redis did not start in time")
        return False
    except Exception as e:
        log(f"ERROR starting local Redis: {e}")
        return False

def stop_local_redis():
    global _local_redis_proc
    if _local_redis_proc:
        try:
            _local_redis_proc.terminate()
            _local_redis_proc.wait(timeout=5)
            log("Local Redis stopped")
        except Exception:
            pass
        _local_redis_proc = None

# ── bench runner ──────────────────────────────────────────────────────────────
def get_env():
    return {
        **os.environ,
        "PATH": "/usr/local/bin:/home/frappe/.local/bin:/home/frappe/frappe-bench/env/bin:" + os.environ.get("PATH", ""),
    }

def run_bench(args, timeout=600):
    cmd = ["/usr/local/bin/bench"] + [str(a) for a in args]
    log(f"$ {' '.join(cmd)}")
    try:
        proc = subprocess.Popen(
            cmd, cwd=BENCH_DIR, env=get_env(),
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1
        )
        deadline = time.time() + timeout
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                log(f"  > {line}")
            if time.time() > deadline:
                proc.kill()
                log(f"ERROR: timed out after {timeout}s")
                return -1
        proc.wait()
        log(f"  exit: {proc.returncode}")
        return proc.returncode
    except Exception as e:
        log(f"ERROR running bench: {e}")
        return -1

def run_mysql(sql, user="root", password=None, db=None, timeout=60):
    password = password or DB_ROOT
    cmd = ["mysql", f"-h{DB_HOST}", f"-P{DB_PORT}", f"-u{user}", f"-p{password}",
           "--connect-timeout=10"]
    if db:
        cmd.append(db)
    try:
        r = subprocess.run(cmd, input=sql, capture_output=True, text=True,
                           timeout=timeout, env=get_env())
        if r.returncode != 0:
            log(f"  mysql error: {r.stderr.strip()[:400]}")
        return r.returncode
    except Exception as e:
        log(f"  mysql exception: {e}")
        return -1

def db_exists():
    """Check if the crm_db database already exists in MariaDB."""
    sql = f"SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='{DB_NAME}';"
    cmd = ["mysql", f"-h{DB_HOST}", f"-P{DB_PORT}", f"-uroot", f"-p{DB_ROOT}",
           "--connect-timeout=10", "-N", "-s", "-e", sql]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=get_env())
        result = r.stdout.strip()
        log(f"DB check: '{result}' (rc={r.returncode})")
        return result == DB_NAME
    except Exception as e:
        log(f"DB check exception: {e}")
        return False

def count_doctypes():
    """Count rows in tabDocType to see how far bench new-site got."""
    sql = f"SELECT COUNT(*) FROM `{DB_NAME}`.tabDocType;"
    cmd = ["mysql", f"-h{DB_HOST}", f"-P{DB_PORT}", f"-uroot", f"-p{DB_ROOT}",
           "--connect-timeout=10", "-N", "-s", "-e", sql]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=get_env())
        result = r.stdout.strip()
        count = int(result) if result.isdigit() else 0
        log(f"tabDocType rows: {count}")
        return count
    except Exception as e:
        log(f"DocType count exception: {e}")
        return 0

def import_baked_db():
    """Import the baked SQL dump into MariaDB. Returns True on success."""
    log(f"Importing baked DB from {BAKED_DB_PATH}...")
    log(f"  File size: {os.path.getsize(BAKED_DB_PATH):,} bytes (compressed)")

    # Create DB and user first
    setup_sql = f"""
CREATE DATABASE IF NOT EXISTS `{DB_NAME}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '{DB_NAME}'@'%' IDENTIFIED BY '{DB_PASS}';
GRANT ALL PRIVILEGES ON `{DB_NAME}`.* TO '{DB_NAME}'@'%';
CREATE USER IF NOT EXISTS '{DB_NAME}'@'localhost' IDENTIFIED BY '{DB_PASS}';
GRANT ALL PRIVILEGES ON `{DB_NAME}`.* TO '{DB_NAME}'@'localhost';
FLUSH PRIVILEGES;
"""
    rc = run_mysql(setup_sql)
    if rc != 0:
        log("ERROR: Failed to create DB/user")
        return False

    # Import the gzipped dump
    cmd_str = (
        f"zcat {BAKED_DB_PATH} | "
        f"mysql -h{DB_HOST} -P{DB_PORT} -u{DB_NAME} -p{DB_PASS} "
        f"--connect-timeout=10 {DB_NAME}"
    )
    log(f"$ {cmd_str}")
    try:
        r = subprocess.run(
            cmd_str, shell=True, capture_output=True, text=True,
            timeout=300, env=get_env()
        )
        if r.returncode != 0:
            log(f"  import error (rc={r.returncode}): {r.stderr.strip()[:400]}")
            return False
        log("  Baked DB import OK")
        return True
    except Exception as e:
        log(f"  import exception: {e}")
        return False

# ── Site config helpers ───────────────────────────────────────────────────────
def write_common_site_config(redis_cache_url, redis_queue_url):
    path = os.path.join(BENCH_DIR, "sites", "common_site_config.json")
    try:
        with open(path) as f:
            cfg = json.load(f)
    except Exception:
        cfg = {}
    cfg["redis_cache"]    = redis_cache_url
    cfg["redis_queue"]    = redis_queue_url
    cfg["redis_socketio"] = redis_queue_url
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
    log(f"common_site_config.json: redis_cache={redis_cache_url}")

def write_site_config():
    site_dir = os.path.join(BENCH_DIR, "sites", SITE)
    os.makedirs(os.path.join(site_dir, "logs"), exist_ok=True)
    cfg = {
        "db_name":     DB_NAME,
        "db_password": DB_PASS,
        "db_host":     DB_HOST,
        "db_port":     DB_PORT,
    }
    if ENC_KEY:
        cfg["encryption_key"] = ENC_KEY
    path = os.path.join(site_dir, "site_config.json")
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
    log(f"site_config.json written for {SITE}")

def crm_app_installed():
    """Check if CRM app is already installed in the site."""
    sql = f"SELECT COUNT(*) FROM `{DB_NAME}`.tabInstalledApplications WHERE app_name='crm';"
    cmd = ["mysql", f"-h{DB_HOST}", f"-P{DB_PORT}", f"-uroot", f"-p{DB_ROOT}",
           "--connect-timeout=10", "-N", "-s", "-e", sql]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=get_env())
        result = r.stdout.strip()
        count = int(result) if result.isdigit() else 0
        log(f"CRM app installed: {count > 0} (count={count})")
        return count > 0
    except Exception as e:
        log(f"CRM check exception: {e}")
        return False

# ── Setup logic ───────────────────────────────────────────────────────────────
def setup_site():
    global SETUP_SUCCESS
    try:
        _setup_site_inner()
    except Exception as e:
        import traceback
        log(f"FATAL: {e}")
        log(traceback.format_exc())
    finally:
        SETUP_DONE.set()

def _setup_site_inner():
    global SETUP_SUCCESS

    log(f"=== Setup start {time.strftime('%Y-%m-%d %H:%M:%S')} ===")
    log(f"SITE={SITE}  DB={DB_HOST}:{DB_PORT}/{DB_NAME}  PORT={SERVE_PORT}")
    log(f"DB_ROOT={'set' if DB_ROOT else 'MISSING'}  ADMIN_PW={'set' if ADMIN_PW else 'MISSING'}")
    log(f"REDIS_CACHE={REDIS_CACHE}  REDIS_QUEUE={REDIS_QUEUE}")
    log(f"Baked DB available: {os.path.exists(BAKED_DB_PATH)}")

    # 1. Start local Redis
    if not start_local_redis():
        log("WARNING: Local Redis failed to start — migrate may fail")

    # 2. Point common_site_config at local Redis
    write_common_site_config(LOCAL_REDIS_URL, LOCAL_REDIS_URL)

    # 3. Wait for MariaDB
    if not wait_for_tcp(DB_HOST, DB_PORT, "MariaDB", timeout=300):
        log("ERROR: MariaDB unreachable after 5 min — aborting")
        return
    time.sleep(3)

    # 4. Determine boot mode
    site_config_path = os.path.join(BENCH_DIR, "sites", SITE, "site_config.json")
    site_exists = os.path.exists(site_config_path)
    log(f"Site config exists on disk: {site_exists}")

    if site_exists:
        # ── FAST PATH: subsequent boots ──────────────────────────────────────
        log("=== SUBSEQUENT BOOT: bench migrate (~30s) ===")
        rc = run_bench(["--site", SITE, "migrate", "--skip-search-index"], timeout=600)
        if rc == 0:
            log("Migrate succeeded!")
        else:
            log(f"Migrate returned rc={rc} — continuing anyway")
        run_bench(["use", SITE])
        SETUP_SUCCESS = True
        log(f"=== Ready {time.strftime('%H:%M:%S')} ===")
        return

    # site_config.json does NOT exist — check if DB exists (crash resume)
    db_already_exists = db_exists()
    log(f"DB exists in MariaDB: {db_already_exists}")

    if db_already_exists:
        # ── RESUME PATH: previous run crashed mid-setup ───────────────────────
        dt_count = count_doctypes()
        log(f"=== RESUME BOOT: DB exists with {dt_count} DocTypes ===")

        if dt_count >= 100:
            log(f"Sufficient DocTypes ({dt_count}) — writing site_config and running migrate")
            write_site_config()
            rc = run_bench(["--site", SITE, "migrate", "--skip-search-index"], timeout=3600)
            if rc == 0:
                log("Resume migrate succeeded!")
                if not crm_app_installed():
                    log("Installing CRM app...")
                    rc2 = run_bench(["--site", SITE, "install-app", "crm"], timeout=3600)
                    log(f"CRM install rc={rc2}")
                else:
                    log("CRM app already installed")
                run_bench(["use", SITE])
                SETUP_SUCCESS = True
                log(f"=== Resume complete {time.strftime('%H:%M:%S')} ===")
                return
            else:
                log(f"Resume migrate FAILED (rc={rc}) — dropping DB and retrying")
                run_mysql(f"DROP DATABASE IF EXISTS `{DB_NAME}`;")
        else:
            log(f"Too few DocTypes ({dt_count}) — dropping DB and retrying")
            run_mysql(f"DROP DATABASE IF EXISTS `{DB_NAME}`;")

    # ── FIRST BOOT (or retry after drop) ─────────────────────────────────────
    baked_db_available = os.path.exists(BAKED_DB_PATH)

    if baked_db_available:
        # ── FAST FIRST BOOT: import baked DB (~2 min total) ──────────────────
        log("=== FIRST BOOT (baked DB): import + migrate (~2 min) ===")
        log("The baked DB was pre-built by GitHub Actions CI.")

        if not import_baked_db():
            log("ERROR: Baked DB import failed — falling back to bench new-site")
            baked_db_available = False
        else:
            # Write site_config.json so bench can find the site
            write_site_config()

            # Run migrate to apply any schema differences
            log("Running bench migrate to sync schema...")
            rc = run_bench(["--site", SITE, "migrate", "--skip-search-index"], timeout=3600)
            if rc == 0:
                log("Migrate succeeded!")
            else:
                log(f"Migrate returned rc={rc} — continuing anyway")

            # Install CRM app
            if not crm_app_installed():
                log("Installing CRM app...")
                rc2 = run_bench(["--site", SITE, "install-app", "crm"], timeout=3600)
                log(f"CRM install rc={rc2}")
            else:
                log("CRM app already installed in baked DB")

            run_bench(["use", SITE])
            SETUP_SUCCESS = True
            log(f"=== First boot (baked) complete {time.strftime('%H:%M:%S')} ===")
            log("Subsequent boots will skip setup and start in ~30 seconds.")
            return

    if not baked_db_available:
        # ── SLOW FIRST BOOT: bench new-site (~90 min) ────────────────────────
        log("=== FIRST BOOT (no baked DB): bench new-site (~90 min) ===")
        log("This runs ONCE. The result persists on the Render disk.")
        log("Every subsequent boot skips this and starts in ~30 seconds.")
        log("TIP: Rebuild the Docker image to include the baked DB for faster first boot.")

        args = [
            "new-site", SITE,
            "--db-name",        DB_NAME,
            "--db-password",    DB_PASS,
            "--admin-password", ADMIN_PW,
            "--db-host",        DB_HOST,
            "--db-port",        str(DB_PORT),
            "--mariadb-user-host-login-scope", "%",
            "--verbose",
            "--force",
        ]
        if DB_ROOT:
            args += ["--db-root-password", DB_ROOT]

        log("bench new-site started. Check /setup-log for progress.")
        rc = run_bench(args, timeout=18000)  # 5 hours — effectively no timeout

        if rc != 0:
            log(f"bench new-site FAILED (rc={rc})")
            return

        log("bench new-site succeeded!")

        # Install CRM app
        log("Installing CRM app...")
        rc2 = run_bench(["--site", SITE, "install-app", "crm"], timeout=3600)
        if rc2 == 0:
            log("CRM installed!")
        else:
            log(f"CRM install returned rc={rc2} — continuing")

        run_bench(["use", SITE])
        SETUP_SUCCESS = True
        log(f"=== First boot complete {time.strftime('%H:%M:%S')} ===")
        log("Subsequent boots will skip setup and start in ~30 seconds.")

# ── Gunicorn ──────────────────────────────────────────────────────────────────
GUNICORN_CMD = [
    "/home/frappe/frappe-bench/env/bin/gunicorn",
    "--chdir=/home/frappe/frappe-bench/sites",
    f"--bind=0.0.0.0:{SERVE_PORT}",
    "--threads=4",
    "--workers=2",
    "--worker-class=gthread",
    "--worker-tmp-dir=/dev/shm",
    "--timeout=120",
    "--preload",
    "--log-level=info",
    "frappe.app:application",
]

def ensure_assets():
    """
    Rebuild static assets if the assets/ symlink/directory is missing.

    The Render disk is mounted at /home/frappe/frappe-bench/sites, which
    replaces the directory that was in the Docker image layer.  The assets/
    symlink that points back into the app source trees is therefore gone on
    every fresh mount.  Running `bench build` recreates it (~60-90 s).
    """
    assets_path = os.path.join(BENCH_DIR, "sites", "assets")
    frappe_desk_js = os.path.join(assets_path, "frappe", "dist", "js")

    if os.path.isdir(frappe_desk_js):
        log("Assets directory present — skipping bench build")
        return

    log("Assets directory missing (disk mount wiped symlink) — running bench build...")
    rc = run_bench(["build", "--apps", "frappe,erpnext,crm"], timeout=600)
    if rc == 0:
        log("bench build succeeded — assets ready")
    else:
        log(f"bench build returned rc={rc} — gunicorn will start anyway (some assets may 404)")


def exec_gunicorn():
    env = get_env()

    # Rebuild assets if the disk mount wiped the symlink
    ensure_assets()

    # Switch common_site_config to real Redis before gunicorn starts
    log("Switching to real Redis for gunicorn...")
    write_common_site_config(REDIS_CACHE, REDIS_QUEUE)

    # Stop local Redis (gunicorn will use real Redis)
    stop_local_redis()

    gunicorn_bin = GUNICORN_CMD[0]
    if not os.path.exists(gunicorn_bin):
        import glob
        found = glob.glob("/home/frappe/frappe-bench/env/bin/gunicorn*")
        log(f"gunicorn not at expected path, found: {found}")
        if not found:
            log("FATAL: gunicorn not found")
            return
        gunicorn_bin = found[0]

    cs = os.path.join(BENCH_DIR, "sites", "currentsite.txt")
    if not os.path.exists(cs):
        with open(cs, "w") as f:
            f.write(SITE)
        log(f"Wrote currentsite.txt = {SITE}")
    else:
        log(f"currentsite.txt = {open(cs).read().strip()}")

    r = subprocess.run(
        ["/home/frappe/frappe-bench/env/bin/python", "-c",
         "import frappe.app; print('frappe.app OK')"],
        cwd=os.path.join(BENCH_DIR, "sites"),
        capture_output=True, text=True, env=env, timeout=30
    )
    log(f"frappe.app import: rc={r.returncode} {r.stdout.strip()} {r.stderr.strip()[:200]}")

    log(f"exec gunicorn on port {SERVE_PORT}")
    os.execve(gunicorn_bin, GUNICORN_CMD, env)

# ── Main ──────────────────────────────────────────────────────────────────────
log(f"Starting health server on port {SERVE_PORT}...")
server = HTTPServer(("0.0.0.0", SERVE_PORT), HealthHandler)
server.allow_reuse_address = True
threading.Thread(target=server.serve_forever, daemon=True).start()
log(f"Health server up -> https://crm-frappe-web.onrender.com/setup-log")

threading.Thread(target=setup_site, daemon=True).start()
log("Waiting for setup...")
SETUP_DONE.wait()

if SETUP_SUCCESS:
    log("Setup succeeded -> starting gunicorn")
    server.shutdown()
    exec_gunicorn()
else:
    log("Setup FAILED -> keeping health server alive. Check /setup-log.")
    log("Fix the error and trigger a manual redeploy in Render dashboard.")
    while True:
        time.sleep(300)
        log("Still alive (setup failed). Check /setup-log.")
