dbfilename redis_queue.rdb
dir /Users/fahadkiani/Desktop/development/crm-develop/frappe-bench/config/pids
pidfile /Users/fahadkiani/Desktop/development/crm-develop/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/fahadkiani/Desktop/development/crm-develop/frappe-bench/config/redis_queue.acl
