<script setup>
import { ref, nextTick } from 'vue'

const loading = ref(false)
const error = ref('')
const results = ref([])
const company = ref('')
const domain = ref('')
const intel = ref(null)

// ── Farfalle Chat State ──────────────────────────────
const chatInput = ref('')
const chatMessages = ref([])
const chatLoading = ref(false)
const chatSources = ref([])

function getFarfalleBase() {
  if (window.FARFALLE_BASE) return String(window.FARFALLE_BASE)
  // EAIA backend has Farfalle-compatible /chat endpoint
  return 'http://localhost:8001'
}

// ── Company Intelligence ──────────────────────────────
async function analyze() {
  loading.value = true
  error.value = ''
  intel.value = null
  try {
    const base = getFarfalleBase()
    const resp = await fetch(`${base}/intel/enrich_lead`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ company: company.value, domain: domain.value })
    })
    if (!resp.ok) throw new Error(`Intel failed (${resp.status})`)
    intel.value = await resp.json()
  } catch (e) {
    error.value = e?.message || 'Failed — is Farfalle running?'
  } finally {
    loading.value = false
  }
}

// ── Farfalle SSE Chat ──────────────────────────────
async function sendChat() {
  const query = chatInput.value.trim()
  if (!query || chatLoading.value) return

  chatMessages.value.push({ role: 'user', content: query })
  chatInput.value = ''
  chatLoading.value = true
  chatSources.value = []

  // Add placeholder for assistant response
  const assistantIdx = chatMessages.value.length
  chatMessages.value.push({ role: 'assistant', content: '', sources: [], loading: true })

  await nextTick()
  scrollChatToBottom()

  try {
    const base = getFarfalleBase()
    const resp = await fetch(`${base}/chat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        query: query,
        history: chatMessages.value.slice(0, -1).map(m => ({
          content: m.content,
          role: m.role
        })),
        model: 'gpt-4o-mini',
        pro_search: false,
      })
    })

    if (!resp.ok) throw new Error(`Chat failed (${resp.status})`)

    const reader = resp.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''

    while (true) {
      const { done, value } = await reader.read()
      if (done) break

      buffer += decoder.decode(value, { stream: true })
      const lines = buffer.split('\n')
      buffer = lines.pop() || ''

      for (const line of lines) {
        if (!line.startsWith('data:')) continue
        const jsonStr = line.slice(5).trim()
        if (!jsonStr) continue

        try {
          const evt = JSON.parse(jsonStr)
          const data = evt.data || evt

          if (data.event_type === 'text-chunk' && data.text) {
            chatMessages.value[assistantIdx].content += data.text
            scrollChatToBottom()
          } else if (data.event_type === 'search-results' && data.results) {
            chatMessages.value[assistantIdx].sources = data.results.map(r => ({
              title: r.title,
              url: r.url
            }))
            chatSources.value = chatMessages.value[assistantIdx].sources
          } else if (data.event_type === 'related-queries' && data.related_queries) {
            chatMessages.value[assistantIdx].relatedQueries = data.related_queries
          }
        } catch {
          // Skip malformed SSE lines
        }
      }
    }
  } catch (e) {
    chatMessages.value[assistantIdx].content = `Error: ${e.message}. Is Farfalle running at ${getFarfalleBase()}?`
    chatMessages.value[assistantIdx].isError = true
  } finally {
    chatMessages.value[assistantIdx].loading = false
    chatLoading.value = false
  }
}

function scrollChatToBottom() {
  nextTick(() => {
    const el = document.querySelector('.chat-messages')
    if (el) el.scrollTop = el.scrollHeight
  })
}

function askFollowUp(q) {
  chatInput.value = q
  sendChat()
}

// ── CRM Integration ──────────────────────────────
async function saveToCRM() {
  if (!intel.value) return
  loading.value = true
  error.value = ''
  try {
    const noteContent = `# Intelligence: ${intel.value.company}\n\n## Summary\n${intel.value.summary.map(s => `- ${s}`).join('\n')}\n\n## Sources\n${(intel.value.results?.flatMap(r => r.sources) || []).map(s => `- [${s.title}](${s.url})`).join('\n')}\n\n---\n*Generated by AI Copilot on ${new Date().toLocaleString()}*`
    await frappe.call({
      method: 'frappe.client.insert',
      args: {
        doc: {
          doctype: 'FCRM Note',
          title: `AI Intel: ${intel.value.company}`,
          content: noteContent,
        }
      }
    })
    alert('Intelligence saved to CRM Notes!')
  } catch (e) {
    error.value = e?.message || 'Failed to save'
  } finally {
    loading.value = false
  }
}

async function demoListOpenLeads() {
  loading.value = true
  error.value = ''
  results.value = []
  try {
    const res = await frappe.call({
      method: 'crm.api.doc.get_data',
      args: {
        doctype: 'CRM Lead',
        filters: { converted: ['=', 0] },
        order_by: 'modified desc',
        page_length: 10
      }
    })
    results.value = res.data?.data || []
  } catch (e) {
    error.value = e?.message || 'Failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="copilot-page">
    <!-- Header -->
    <div class="copilot-header">
      <div class="header-left">
        <span class="header-icon">🧠</span>
        <h1>AI Copilot</h1>
        <span class="powered-by">Powered by Farfalle</span>
      </div>
      <div class="header-right">
        <button class="btn-secondary" @click="demoListOpenLeads" :disabled="loading">
          Top 10 Open Leads
        </button>
      </div>
    </div>

    <div v-if="error" class="error-banner">{{ error }}</div>

    <!-- Main Layout: 2 columns -->
    <div class="copilot-layout">
      <!-- Left: Intel Panel -->
      <div class="intel-panel">
        <div class="panel-header">🔍 Company Intelligence</div>
        <div class="intel-form">
          <input class="form-input" v-model="company" placeholder="Company name (e.g. Abbey Capital)" />
          <input class="form-input" v-model="domain" placeholder="Domain (optional, e.g. abbeycapital.com)" />
          <button class="btn-primary" @click="analyze" :disabled="loading || !company">
            {{ loading ? 'Analyzing…' : 'Analyze' }}
          </button>
        </div>

        <!-- Intel Results -->
        <div v-if="intel" class="intel-results">
          <div class="intel-section">
            <div class="intel-section-header">
              <span>Summary</span>
              <button class="btn-sm" @click="saveToCRM" :disabled="loading">Save to CRM</button>
            </div>
            <ul class="intel-list">
              <li v-for="(b, i) in intel.summary" :key="i">{{ b }}</li>
            </ul>
          </div>

          <div v-if="intel.results?.some(r => r.extracted_people?.length)" class="intel-section">
            <div class="intel-section-header">Decision Makers</div>
            <div v-for="(r, idx) in intel.results" :key="idx">
              <div v-for="(p, pidx) in (r.extracted_people || [])" :key="pidx" class="person-card">
                <strong>{{ p.name }}</strong> — {{ p.title }}
                <a v-if="p.source_url" :href="p.source_url" target="_blank" class="person-link">Profile →</a>
              </div>
            </div>
          </div>

          <div class="intel-section">
            <div class="intel-section-header">Sources ({{ intel.total_sources }})</div>
            <div v-for="(s, i) in (intel.results?.flatMap(r => r.sources) || []).slice(0, 8)" :key="i" class="source-item">
              <a :href="s.url" target="_blank" class="source-link">{{ s.title }}</a>
            </div>
          </div>
        </div>

        <!-- Open Leads List -->
        <div v-if="results.length" class="leads-list">
          <div class="panel-header">Open Leads</div>
          <div v-for="r in results" :key="r.name" class="lead-item">
            <a :href="`/crm/leads/${r.name}`" class="lead-link">{{ r.name }}</a>
            <span class="lead-date">{{ r.modified }}</span>
          </div>
        </div>
      </div>

      <!-- Right: Chat Panel -->
      <div class="chat-panel">
        <div class="panel-header">💬 Farfalle Search Chat</div>

        <div class="chat-messages" ref="chatContainer">
          <div v-if="!chatMessages.length" class="chat-empty">
            <div class="chat-empty-icon">🔱</div>
            <p>Ask anything — company research, market intel, competitive analysis.</p>
            <p class="chat-hint">Examples: "Who are the decision makers at Pfizer?" or "What are recent CRISPR investments?"</p>
          </div>

          <div v-for="(msg, i) in chatMessages" :key="i" :class="['chat-msg', msg.role]">
            <div class="msg-bubble" :class="{ 'msg-error': msg.isError }">
              <div class="msg-content" v-html="formatMessage(msg.content)"></div>
              <div v-if="msg.loading" class="msg-typing">
                <span></span><span></span><span></span>
              </div>
            </div>

            <!-- Sources -->
            <div v-if="msg.sources?.length" class="msg-sources">
              <a v-for="(s, si) in msg.sources.slice(0, 4)" :key="si" :href="s.url" target="_blank" class="source-chip">
                {{ s.title?.slice(0, 40) }}
              </a>
            </div>

            <!-- Related queries -->
            <div v-if="msg.relatedQueries?.length" class="msg-related">
              <button v-for="(q, qi) in msg.relatedQueries" :key="qi" @click="askFollowUp(q)" class="related-btn">
                {{ q }}
              </button>
            </div>
          </div>
        </div>

        <div class="chat-input-area">
          <input
            v-model="chatInput"
            @keydown.enter="sendChat"
            :disabled="chatLoading"
            placeholder="Ask Farfalle anything..."
            class="chat-input"
          />
          <button @click="sendChat" :disabled="chatLoading || !chatInput.trim()" class="send-btn">
            {{ chatLoading ? '…' : '→' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AiCopilot',
  methods: {
    formatMessage(content) {
      if (!content) return ''
      return content
        .replace(/\n/g, '<br>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
    }
  }
}
</script>

<style scoped>
.copilot-page {
  padding: 20px;
  max-width: 1400px;
  margin: 0 auto;
  height: 100%;
  display: flex;
  flex-direction: column;
  font-family: 'Inter', -apple-system, sans-serif;
}

.copilot-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 10px;
}

.header-icon { font-size: 1.5rem; }

.header-left h1 {
  font-size: 1.3rem;
  font-weight: 700;
  color: #1a1a2e;
  margin: 0;
}

.powered-by {
  font-size: 0.7rem;
  color: #8b5cf6;
  background: #ede9fe;
  padding: 2px 8px;
  border-radius: 10px;
  font-weight: 500;
}

.btn-secondary {
  padding: 8px 16px;
  background: white;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.8rem;
  font-weight: 500;
  color: #374151;
  transition: all 0.2s;
}
.btn-secondary:hover { border-color: #8b5cf6; color: #8b5cf6; }
.btn-secondary:disabled { opacity: 0.5; cursor: not-allowed; }

.error-banner {
  background: #fef2f2;
  color: #dc2626;
  padding: 8px 16px;
  border-radius: 8px;
  border: 1px solid #fecaca;
  margin-bottom: 12px;
  font-size: 0.85rem;
}

.copilot-layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  flex: 1;
  min-height: 0;
}

.panel-header {
  font-size: 0.85rem;
  font-weight: 600;
  color: #374151;
  padding: 12px 16px;
  border-bottom: 1px solid #e5e7eb;
}

/* Intel Panel */
.intel-panel {
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  overflow-y: auto;
}

.intel-form {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-input {
  padding: 10px 12px;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  font-size: 0.85rem;
  transition: border-color 0.2s;
}
.form-input:focus { border-color: #8b5cf6; outline: none; box-shadow: 0 0 0 2px rgba(139, 92, 246, 0.1); }

.btn-primary {
  padding: 10px 16px;
  background: #8b5cf6;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  font-size: 0.85rem;
  transition: background 0.2s;
}
.btn-primary:hover { background: #7c3aed; }
.btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }

.btn-sm {
  padding: 4px 10px;
  background: #8b5cf6;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 0.7rem;
  font-weight: 600;
}
.btn-sm:disabled { opacity: 0.5; }

.intel-results { padding: 0 16px 16px; }

.intel-section {
  margin-top: 16px;
}

.intel-section-header {
  font-size: 0.8rem;
  font-weight: 600;
  color: #6b7280;
  margin-bottom: 8px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.intel-list {
  list-style: disc;
  margin: 0;
  padding-left: 20px;
  font-size: 0.82rem;
  color: #374151;
  line-height: 1.6;
}

.person-card {
  padding: 8px 12px;
  background: #f9fafb;
  border-radius: 8px;
  font-size: 0.82rem;
  margin-bottom: 4px;
}

.person-link {
  color: #8b5cf6;
  text-decoration: none;
  margin-left: 8px;
  font-size: 0.75rem;
}

.source-item {
  padding: 4px 0;
}

.source-link {
  color: #2563eb;
  text-decoration: none;
  font-size: 0.8rem;
}
.source-link:hover { text-decoration: underline; }

.leads-list { padding: 0 16px 16px; }

.lead-item {
  display: flex;
  justify-content: space-between;
  padding: 8px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  margin-top: 8px;
}

.lead-link {
  color: #2563eb;
  text-decoration: none;
  font-size: 0.85rem;
}

.lead-date {
  color: #9ca3af;
  font-size: 0.75rem;
}

/* Chat Panel */
.chat-panel {
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.chat-empty {
  text-align: center;
  padding: 40px 20px;
  color: #9ca3af;
}

.chat-empty-icon { font-size: 2.5rem; margin-bottom: 12px; }
.chat-empty p { margin: 4px 0; font-size: 0.85rem; }
.chat-hint { font-size: 0.75rem !important; color: #c4b5fd; font-style: italic; }

.chat-msg { display: flex; flex-direction: column; }
.chat-msg.user { align-items: flex-end; }
.chat-msg.assistant { align-items: flex-start; }

.msg-bubble {
  max-width: 85%;
  padding: 10px 14px;
  border-radius: 12px;
  font-size: 0.85rem;
  line-height: 1.5;
}

.user .msg-bubble {
  background: #8b5cf6;
  color: white;
  border-bottom-right-radius: 4px;
}

.assistant .msg-bubble {
  background: #f3f4f6;
  color: #1f2937;
  border-bottom-left-radius: 4px;
}

.msg-error {
  background: #fef2f2 !important;
  color: #dc2626 !important;
  border: 1px solid #fecaca;
}

.msg-typing {
  display: flex;
  gap: 4px;
  padding: 4px 0;
}

.msg-typing span {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #9ca3af;
  animation: bounce 1.4s infinite ease-in-out;
}
.msg-typing span:nth-child(1) { animation-delay: 0s; }
.msg-typing span:nth-child(2) { animation-delay: 0.2s; }
.msg-typing span:nth-child(3) { animation-delay: 0.4s; }

@keyframes bounce {
  0%, 80%, 100% { transform: scale(0.6); opacity: 0.5; }
  40% { transform: scale(1); opacity: 1; }
}

.msg-sources {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 6px;
}

.source-chip {
  padding: 3px 8px;
  background: #ede9fe;
  color: #7c3aed;
  border-radius: 6px;
  font-size: 0.65rem;
  text-decoration: none;
  transition: background 0.2s;
}
.source-chip:hover { background: #ddd6fe; }

.msg-related {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 8px;
}

.related-btn {
  padding: 4px 10px;
  background: #f0fdf4;
  color: #16a34a;
  border: 1px solid #bbf7d0;
  border-radius: 6px;
  font-size: 0.7rem;
  cursor: pointer;
  transition: all 0.2s;
}
.related-btn:hover { background: #dcfce7; border-color: #86efac; }

.chat-input-area {
  display: flex;
  gap: 8px;
  padding: 12px 16px;
  border-top: 1px solid #e5e7eb;
}

.chat-input {
  flex: 1;
  padding: 10px 14px;
  border: 1px solid #d1d5db;
  border-radius: 10px;
  font-size: 0.85rem;
  transition: border-color 0.2s;
}
.chat-input:focus { border-color: #8b5cf6; outline: none; }

.send-btn {
  width: 40px;
  height: 40px;
  background: #8b5cf6;
  color: white;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  font-size: 1.1rem;
  font-weight: 700;
  transition: background 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}
.send-btn:hover { background: #7c3aed; }
.send-btn:disabled { opacity: 0.5; cursor: not-allowed; }

@media (max-width: 768px) {
  .copilot-layout {
    grid-template-columns: 1fr;
  }
}
</style>
